Change np.inf to np.Inf in get_ratio_threshold
I received an attribute error when trying to run the sample data from your readme mile.

AttributeError: `np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.

I believe this would help resolve it.